apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-experiment-large
  labels:
    scenario: "06-pod-sizing-large"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-experiment-large
  template:
    metadata:
      labels:
        app: java-experiment-large
    spec:
      containers:
        - name: app
          image: java-experiment:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1500m"
            limits:
              memory: "1Gi"
              cpu: "1500m"
---
apiVersion: v1
kind: Service
metadata:
  name: java-experiment-large
spec:
  selector:
    app: java-experiment-large
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
