apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-experiment
  labels:
    scenario: "16-zgc-prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-experiment
  template:
    metadata:
      labels:
        app: java-experiment
    spec:
      containers:
        - name: app
          image: java-experiment:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseZGC -XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=75.0 -XX:MinRAMPercentage=75.0 -XX:+AlwaysPreTouch -XX:+ExitOnOutOfMemoryError"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: java-experiment
spec:
  selector:
    app: java-experiment
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
